import { Link, useParams } from 'react-router-dom'
import Layout from '../components/Layout'
import { destinations } from '../data/mockTravelData'
import { useTrip } from '../components/useTrip'
import { Button, Tag } from '../components/ui'

export default function Summary() {
  const { id } = useParams()
  const { preferences, selectedDestination } = useTrip()
  const destination = selectedDestination || destinations.find(item => item.id === id || item.id.startsWith(id)) || destinations[0]
  const total = Number(destination.estimatedCost || destination.cost || 0) * preferences.travellers
  const score = destination.matchScore || destination.score || 80

  return <Layout compact><section className="summary-page"><div className="container"><div className="summary-hero"><div><span className="eyebrow">Trip ready</span><h1>Your trip is ready. <em>✦</em></h1><p>A thoughtfully matched plan built around your choices and your pace.</p></div><div className="summary-destination"><span>Destination</span><strong>{destination.name}</strong><small>{destination.region || destination.country} · {score}% match</small></div></div><div className="summary-layout"><div className="summary-main"><div className="summary-stats"><div><span>Duration</span><strong>{preferences.duration}</strong></div><div><span>Travellers</span><strong>{preferences.travellers}</strong></div><div><span>Per person</span><strong>₹{Number(destination.estimatedCost || destination.cost || 0).toLocaleString('en-IN')}</strong></div><div className="summary-total"><span>Total trip</span><strong>₹{total.toLocaleString('en-IN')}</strong></div></div><div className="summary-card"><div className="summary-card-head"><div><span className="eyebrow">Trip breakdown</span><h2>Where your budget goes</h2></div><span className="match-badge">{score}% Trip Match</span></div><div className="breakdown-list"><div><span><i className="dot coral" />Transport</span><strong>₹4,800</strong></div><div><span><i className="dot navy" />Stay</span><strong>₹3,600</strong></div><div><span><i className="dot green" />Food</span><strong>₹2,400</strong></div><div><span><i className="dot gold" />Activities</span><strong>₹2,100</strong></div></div><div className="breakdown-total"><span>Total per person</span><strong>₹{Number(destination.estimatedCost || destination.cost || 0).toLocaleString('en-IN')}</strong></div></div><div className="highlights-card"><span className="eyebrow">Your trip highlights</span><h2>All the moments that made the cut.</h2><div className="highlight-tags">{(destination.tags || []).map(tag => <Tag key={tag} tone={tag === 'Food' ? 'orange' : tag === 'Nature' ? 'green' : 'neutral'}>{tag}</Tag>)}</div><div className="highlight-list"><span>✓ {destination.name} local discovery</span><span>✓ Budget and pace matched</span><span>✓ Flexible itinerary controls</span><span>✓ Data source clearly shown</span></div></div></div><aside className="summary-aside"><div className="summary-card summary-ready"><span className="ready-spark">✦</span><h3>Ready for the next step?</h3><p>Save, share or continue refining your itinerary.</p><Button to={`/itinerary/${destination.id}`} variant="secondary" className="full-width">View full itinerary</Button><Button to="/plan" variant="outline" className="full-width">Start new trip</Button><button type="button" className="share-button"><span>↗</span> Share trip</button></div><div className="summary-mobile-side"><Link to={`/itinerary/${destination.id}`}>View itinerary <span>→</span></Link></div></aside></div></div></section></Layout>
}
